spring:
  application:
    name: api-gateway

info:
  component: Api gateway

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    persons-server:
      path: /person/**
    cars-server:
      path: /car/**
    mailing-server:
      path: /mail/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO